services:
  frontend:
    image: ghcr.io/pascalnehlsen/conduit-frontend:${github.sha}
    ports:
      - 8282:80
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - conduit-network

  backend:
    image: ghcr.io/pascalnehlsen/conduit-backend:${github.sha}
    env_file:
      - .env
    volumes:
      - conduit-backend:/app/db_data
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - conduit-network

volumes:
  conduit-backend:

networks:
  conduit-network:
    driver: bridge
