services:
  frontend:
    build:
      context: .
      dockerfile: conduit-frontend/frontend.Dockerfile
    ports:
      - 8282:80
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: conduit-backend/backend.Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
