services:
  frontend:
    build:
      context: .
      dockerfile: conduit-frontend/frontend.Dockerfile
    ports:
      - 8282:80
    restart: on-failure
    networks:
      - conduit-network

  backend:
    build:
      context: .
      dockerfile: conduit-backend/backend.Dockerfile
    env_file:
      - .env
    volumes:
      - conduit:/app/db_data
    ports:
      - 8000:8000
    restart: on-failure
    networks:
      - conduit-network

volumes:
  conduit:

networks:
  conduit-network:
    driver: bridge
