name: Create PR from dev to main

on:
  workflow_call:
    secrets:
      PAT:
        required: true
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7.0.6
        with:
          token: ${{ secrets.PAT }}
          committer: PascalNehlsen <pascaldev92@gmail.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: dev
          base: main
          delete-branch: true
          labels: |
            automated pr

      - name: Run Frontend Tests
        id: frontend-tests
        run: |
          cd conduit-frontend
          echo "Running frontend tests..."

      - name: Run Backend Tests
        id: backend-tests
        run: |
          cd conduit-backend
          echo "Running backend tests..."

      # - name: Enable Pull Request Automerge
      #   if: steps.frontend-tests.outcome == 'success' && steps.backend-tests.outcome == 'success' && steps.cpr.outputs.pull-request-operation == 'created'
      #   uses: peter-evans/enable-pull-request-automerge@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
      #     merge-method: squash
