name: CI/CD Workflow

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  create-or-update-pr:
    uses: ./.github/workflows/create-or-update-pr.yml
    secrets:
      PAT: ${{ secrets.PAT }}

  clone-repo-with-rsync:
    uses: ./.github/workflows/deployment.yml
    needs: create-or-update-pr
