name: CI/CD Workflow

on:
  workflow_dispatch:

jobs:
  create-or-update-pr:
    uses: ./.github/workflows/create-or-update-pr.yml
    secrets:
      PAT: ${{ secrets.PAT }}

  clone-repo-with-rsync:
    uses: ./.github/workflows/deployment.yml
    needs: create-or-update-pr
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      TARGET: ${{ secrets.PATH }}
